/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: a.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "a.pb-c.h"
void   person__phone_number__init
                     (Person__PhoneNumber         *message)
{
  static Person__PhoneNumber init_value = PERSON__PHONE_NUMBER__INIT;
  *message = init_value;
}
void   person__init
                     (Person         *message)
{
  static Person init_value = PERSON__INIT;
  *message = init_value;
}
size_t person__get_packed_size
                     (const Person *message)
{
  assert(message->base.descriptor == &person__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t person__pack
                     (const Person *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &person__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t person__pack_to_buffer
                     (const Person *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &person__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Person *
       person__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Person *)
     protobuf_c_message_unpack (&person__descriptor,
                                allocator, len, data);
}
void   person__free_unpacked
                     (Person *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &person__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const Person__PhoneType person__phone_number__type__default_value = PERSON__PHONE_TYPE__HOME;
static const ProtobufCFieldDescriptor person__phone_number__field_descriptors[2] =
{
  {
    "number",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Person__PhoneNumber, number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Person__PhoneNumber, has_type),
    offsetof(Person__PhoneNumber, type),
    &person__phone_type__descriptor,
    &person__phone_number__type__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned person__phone_number__field_indices_by_name[] = {
  0,   /* field[0] = number */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange person__phone_number__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor person__phone_number__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Person.PhoneNumber",
  "PhoneNumber",
  "Person__PhoneNumber",
  "",
  sizeof(Person__PhoneNumber),
  2,
  person__phone_number__field_descriptors,
  person__phone_number__field_indices_by_name,
  1,  person__phone_number__number_ranges,
  (ProtobufCMessageInit) person__phone_number__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue person__phone_type__enum_values_by_number[3] =
{
  { "MOBILE", "PERSON__PHONE_TYPE__MOBILE", 0 },
  { "HOME", "PERSON__PHONE_TYPE__HOME", 1 },
  { "WORK", "PERSON__PHONE_TYPE__WORK", 2 },
};
static const ProtobufCIntRange person__phone_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex person__phone_type__enum_values_by_name[3] =
{
  { "HOME", 1 },
  { "MOBILE", 0 },
  { "WORK", 2 },
};
const ProtobufCEnumDescriptor person__phone_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Person.PhoneType",
  "PhoneType",
  "Person__PhoneType",
  "",
  3,
  person__phone_type__enum_values_by_number,
  3,
  person__phone_type__enum_values_by_name,
  1,
  person__phone_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor person__field_descriptors[4] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Person, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Person, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "age",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Person, age),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "phone",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Person, n_phone),
    offsetof(Person, phone),
    &person__phone_number__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned person__field_indices_by_name[] = {
  2,   /* field[2] = age */
  1,   /* field[1] = id */
  0,   /* field[0] = name */
  3,   /* field[3] = phone */
};
static const ProtobufCIntRange person__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor person__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Person",
  "Person",
  "Person",
  "",
  sizeof(Person),
  4,
  person__field_descriptors,
  person__field_indices_by_name,
  1,  person__number_ranges,
  (ProtobufCMessageInit) person__init,
  NULL,NULL,NULL    /* reserved[123] */
};
